/*
 * ws2812b.c — WS2812B driver for STM32L432KC
 *
 * Uses TIM1 CH1 PWM + DMA1 Channel 2 in circular mode.
 * Architecture follows MaJerle's TIM/PWM/DMA pattern:
 *   https://github.com/MaJerle/stm32-ws2811-ws2812-ws2812b-ws281x-tim-pwm-dma-timer
 *
 * The DMA buffer holds 2 × 24 slots (two LEDs worth of PWM compare values).
 * HT fires when the first half is consumed → refill first half.
 * TC fires when the second half is consumed → refill second half.
 * A state machine tracks where we are in the full sequence:
 *   RESET_START → LED DATA → RESET_END → idle (loop back).
 */

#include "ws2812b.h"
#include "main.h"          /* Generated by CubeMX — exposes htim1  */
#include <string.h>
extern TIM_HandleTypeDef htim1;

/* ── Internal state ─────────────────────────────────────────────────── */

/* Colour store (GRB order, as WS2812B expects G first)                 */
static uint8_t led_g[WS2812B_NUM_LEDS];
static uint8_t led_r[WS2812B_NUM_LEDS];
static uint8_t led_b[WS2812B_NUM_LEDS];

/* DMA working buffer — two half-buffers of 24 slots each               */
static volatile uint16_t dma_buf[WS2812B_BUF_SIZE];

typedef enum {
    STATE_RESET_START,  /* Emit reset pulse before data               */
    STATE_DATA,         /* Streaming LED bits                         */
    STATE_RESET_END,    /* Emit reset pulse after all LEDs            */
} ws_state_t;

static volatile ws_state_t  state;
static volatile uint16_t    led_index;      /* Current LED being sent  */
static volatile uint16_t    reset_counter;  /* Counts reset periods    */

/* ── Helpers ─────────────────────────────────────────────────────────── */

/**
 * Encode one LED's GRB bytes into 24 PWM compare values
 * starting at buf[offset].  WS2812B transmits MSB first.
 */
static void encode_led(volatile uint16_t *buf, uint16_t index) {
    uint8_t bytes[3] = { led_g[index], led_r[index], led_b[index] };
    for (int byte = 0; byte < 3; byte++) {
        for (int bit = 7; bit >= 0; bit--) {
            *buf++ = (bytes[byte] & (1 << bit)) ? WS2812B_PWM_HI : WS2812B_PWM_LO;
        }
    }
}

/**
 * Fill one half-buffer (24 slots) according to current state.
 */
static void fill_half(volatile uint16_t *buf) {
    switch (state) {
        case STATE_RESET_START:
            memset((void *)buf, 0, 24 * sizeof(uint16_t));
            reset_counter++;
            if (reset_counter >= WS2812B_RESET_PERIODS) {
                reset_counter = 0;
                state = STATE_DATA;
                led_index = 0;
            }
            break;

        case STATE_DATA:
            if (led_index < WS2812B_NUM_LEDS) {
                encode_led(buf, led_index++);
            } else {
                /* All LEDs sent — start trailing reset                 */
                memset((void *)buf, 0, 24 * sizeof(uint16_t));
                state = STATE_RESET_END;
                reset_counter = 1;
            }
            break;

        case STATE_RESET_END:
            memset((void *)buf, 0, 24 * sizeof(uint16_t));
            reset_counter++;
            if (reset_counter >= WS2812B_RESET_PERIODS) {
                /* One full frame done — loop back to start            */
                reset_counter = 0;
                state = STATE_RESET_START;
                led_index = 0;
            }
            break;
    }
}

/* ── Public API ──────────────────────────────────────────────────────── */

void WS2812B_Init(void) {
    memset(led_g, 0, sizeof(led_g));
    memset(led_r, 0, sizeof(led_r));
    memset(led_b, 0, sizeof(led_b));
    memset((void *)dma_buf, 0, sizeof(dma_buf));

    state = STATE_RESET_START;
    led_index = 0;
    reset_counter = 0;

    /* Start PWM DMA — CubeMX handle is htim1, channel TIM_CHANNEL_1   */
    HAL_TIM_PWM_Start_DMA(&htim1,
                           TIM_CHANNEL_1,
                           (uint32_t *)dma_buf,
                           WS2812B_BUF_SIZE);
}

void WS2812B_SetLED(uint16_t index, uint8_t r, uint8_t g, uint8_t b) {
    if (index >= WS2812B_NUM_LEDS) return;
    led_r[index] = r;
    led_g[index] = g;
    led_b[index] = b;
}

void WS2812B_Clear(void) {
    memset(led_r, 0, sizeof(led_r));
    memset(led_g, 0, sizeof(led_g));
    memset(led_b, 0, sizeof(led_b));
}

/* ── DMA callbacks (wire these up in stm32l4xx_it.c or tim.c) ────────── */

/* Called when first half of dma_buf has been consumed                    */
void WS2812B_DMA_HalfCpltCallback(void) {
    fill_half(&dma_buf[0]);          /* Refill first half               */
}

/* Called when second half of dma_buf has been consumed                   */
void WS2812B_DMA_CpltCallback(void) {
    fill_half(&dma_buf[24]);         /* Refill second half              */
}
